### ISSUE TITLE
How to publish public folder to my public/shopper ?

### ISSUE THREAD

**Issue by picbenoit** [shopperlabs/shopper#10]
Hello,

I forked your project yesterday cause I want to add a "name" field to "addresses" table. a shopper user can have multiple addresses so it can be well to let the user named it.
If you are ok, I can make a PR after I valid my dev.

But I didn't find a way (artisan command) to move the public shopper folder to my project "public/shopper" folder. republish command do not do this staff.

Also @mckenziearts @fabriceyopa, do you need help to add some feature on shopper ? I am particularly interested about attributes and translate message.

**Comment by picbenoit** [comment]
A way I think about is to add this line in my webpack project :

`mix.copyDirectory('/vendor/mckenziearts/shopper/public', 'public/shopper');`

It will work think so.

Ben.

**Comment by mckenziearts** [comment]
Hello to publish files you have to run this command : `php artisan shopper:link`

**Comment by picbenoit** [comment]
Hello,

The command is not working because the shopper folder is still there.

To update my changes on my project I delete the folder and copy it from the vendor folder.

The problem will be there also when you update shopper and not only on fork repo.
