### ISSUE TITLE
Make more obvious that the product price must be set in cents through the dashboard

### ISSUE THREAD

**Issue by iagobruno** [shopperlabs/shopper#128]
I'm testing Shopper and faced troubles to setting a price for a product through the dashboard. I tried setting the price to 72.99 (seventy-two and ninety-nine cents) and saved the product.

![image](https://user-images.githubusercontent.com/3616259/169431045-fbc9f40f-8058-4793-bd71-f533ba1b50bd.png)

But when I checked the product on the catalog list the price was like "0.73".

![image](https://user-images.githubusercontent.com/3616259/169431473-2a7b70f3-c70c-4c21-95a4-4f16381d64ea.png)

Then I tried to set the price in another format like 7299 and I got it.

![image](https://user-images.githubusercontent.com/3616259/169432420-207f3831-9fe2-453f-b634-0ea147447efa.png)
![image](https://user-images.githubusercontent.com/3616259/169434051-dd05e844-b07d-421a-ae52-80f4ac8da8e7.png)

But the format doesn't seem right in the price amount field, it's like the number is "7,299" (seven thousand, two hundred and ninety-nine), for non-programmers this is hard to figure out.
My suggestion is to apply a mask to these fields to force the price to be defined in cents.

**Comment by mckenziearts** [comment]
Done.
