### ISSUE TITLE
Website documentacion is broken

### ISSUE THREAD

**Issue by pabbec** [shopperlabs/shopper#212]
Hi!

It's not a specific Shopper bug, but just to report a problem on the developer website.

The website https://laravelshopper.dev/requirements is broken. All internal pages respond with 500 http error.

**Comment by bdsumon4u** [comment]
![Screenshot from 2023-07-20 21-06-41](https://github.com/shopperlabs/framework/assets/75123992/b74bbe0d-4e0d-4fe1-a319-b2aa33056a5e)

**Comment by kpotia** [comment]
For the meantime you can clone the documentation repository run it localy https://github.com/shopperlabs/laravelshopper.dev

**Comment by mckenziearts** [comment]
Fix everything is up now
