### ISSUE TITLE
Laravel 6 support?

### ISSUE THREAD

**Issue by mwkcoding** [shopperlabs/shopper#25]
Are you planning on making support for Laravel 6?

**Comment by mckenziearts** [comment]
I'm currently work on it.

**Comment by Braunson** [comment]
@mckenziearts This project looks promising, would you be interested in some help to get up to Laravel 8.x?

**Comment by mckenziearts** [comment]
In fact we are working on a v2 version which will be available soon. This version will soon be archived once we have set up a script to go from v1 to v2. You can join the discord server to get the information. https://laravelshopper.io
